<body bgcolor="#000000"><font color = "#a0a0a0">//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 Constants0;
//   float4 Constants1;
//   float4 Constants2;
//   sampler2D TexBase;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   Constants0   c0       1
//   Constants1   c1       1
//   Constants2   c2       1
//   TexBase      s0       1
//

</font><font color = "#ffff40">    ps_2_x
    def <font color = "#e0e0e0">c3</font><font color = "#e0e0e0">, </font><font color = "#00ffff">1024</font><font color = "#e0e0e0">, </font><font color = "#00ffff">17</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.159154937</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.5</font><font color = "#a0a0a0"></font>
    def <font color = "#e0e0e0">c4</font><font color = "#e0e0e0">, </font><font color = "#00ffff">2.72154951</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.5</font><font color = "#e0e0e0">, </font><font color = "#00ffff">6.28318548</font><font color = "#e0e0e0">, </font><font color = "#00ffff">-3.14159274</font><font color = "#a0a0a0"></font>
    def <font color = "#e0e0e0">c5</font><font color = "#e0e0e0">, </font><font color = "#00ffff">13</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0</font><font color = "#e0e0e0">, </font><font color = "#00ffff">1</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0</font><font color = "#a0a0a0"></font>
    def <font color = "#e0e0e0">c6</font><font color = "#e0e0e0">, </font><font color = "#00ffff">10000</font><font color = "#e0e0e0">, </font><font color = "#00ffff">2.2281692</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.5</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.100000001</font><font color = "#a0a0a0"></font>
    def <font color = "#e0e0e0">c7</font><font color = "#e0e0e0">, </font><font color = "#00ffff">-1.55009923e-006</font><font color = "#e0e0e0">, </font><font color = "#00ffff">-2.17013894e-005</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.00260416674</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.00026041668</font><font color = "#a0a0a0"></font>
    def <font color = "#e0e0e0">c8</font><font color = "#e0e0e0">, </font><font color = "#00ffff">-0.020833334</font><font color = "#e0e0e0">, </font><font color = "#00ffff">-0.125</font><font color = "#e0e0e0">, </font><font color = "#00ffff">1</font><font color = "#e0e0e0">, </font><font color = "#00ffff">0.5</font><font color = "#a0a0a0"></font>
    dcl <font color = "#e0e0e0">t0.xy</font><font color = "#a0a0a0"></font>
    dcl_2d <font color = "#e0e0e0">s0</font><font color = "#a0a0a0"></font>
    texld <font color = "#e0e0e0">r0</font><font color = "#e0e0e0">, t0</font><font color = "#e0e0e0">, s0</font><font color = "#a0a0a0"></font>
    mov <font color = "#e0e0e0">r1.yz</font><font color = "#e0e0e0">, c6</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, c2.x</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c4.z</font><font color = "#e0e0e0">, c4.w</font><font color = "#a0a0a0"></font>
    sincos <font color = "#e0e0e0">r2.y</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c7</font><font color = "#e0e0e0">, c8</font><font color = "#a0a0a0"></font>
    abs <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r2.y</font><font color = "#a0a0a0"></font>
    add <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c6.w</font><font color = "#a0a0a0"></font>
    mov <font color = "#e0e0e0">r2.xy</font><font color = "#e0e0e0">, c4</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, c2.x</font><font color = "#e0e0e0">, r2.x</font><font color = "#e0e0e0">, r2.y</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c4.z</font><font color = "#e0e0e0">, c4.w</font><font color = "#a0a0a0"></font>
    sincos <font color = "#e0e0e0">r2.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c7</font><font color = "#e0e0e0">, c8</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r2.y</font><font color = "#e0e0e0">, c6.x</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, r1.y</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c2.x</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.xy</font><font color = "#e0e0e0">, t0</font><font color = "#e0e0e0">, c3.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.zw</font><font color = "#e0e0e0">, r1.wzyx</font><font color = "#a0a0a0"></font>
    add <font color = "#e0e0e0">r1.xy</font><font color = "#e0e0e0">, -r1.wzyx</font><font color = "#e0e0e0">, r1</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c6.w</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c3.y</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c5.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c3.z</font><font color = "#e0e0e0">, c3.w</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c4.z</font><font color = "#e0e0e0">, c4.w</font><font color = "#a0a0a0"></font>
    sincos <font color = "#e0e0e0">r2.y</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c7</font><font color = "#e0e0e0">, c8</font><font color = "#a0a0a0"></font>
    abs <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r2.y</font><font color = "#a0a0a0"></font>
    add <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c6.w</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r1.z</font><font color = "#e0e0e0">, c3.z</font><font color = "#e0e0e0">, c3.w</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c4.z</font><font color = "#e0e0e0">, c4.w</font><font color = "#a0a0a0"></font>
    sincos <font color = "#e0e0e0">r2.y</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, c7</font><font color = "#e0e0e0">, c8</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, r2.y</font><font color = "#e0e0e0">, c6.x</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, r1.y</font><font color = "#a0a0a0"></font>
    frc <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#a0a0a0"></font>
    add <font color = "#e0e0e0">r1.y</font><font color = "#e0e0e0">, -r1.x</font><font color = "#e0e0e0">, c0.y</font><font color = "#a0a0a0"></font>
    add <font color = "#e0e0e0">r2.xy</font><font color = "#e0e0e0">, t0</font><font color = "#e0e0e0">, -c4.y</font><font color = "#a0a0a0"></font>
    dp2add <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r2</font><font color = "#e0e0e0">, r2</font><font color = "#e0e0e0">, c5.y</font><font color = "#a0a0a0"></font>
    rsq <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    rcp <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.w</font><font color = "#e0e0e0">, r1.z</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.w</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    mad <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c6.w</font><font color = "#e0e0e0">, r1.z</font><font color = "#a0a0a0"></font>
    mul_sat <font color = "#e0e0e0">r1.w</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c1.y</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r2.xyz</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, c0.z</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.x</font><font color = "#e0e0e0">, r1.w</font><font color = "#e0e0e0">, c1.x</font><font color = "#a0a0a0"></font>
    mul_sat <font color = "#e0e0e0">r1.w</font><font color = "#e0e0e0">, r1.z</font><font color = "#e0e0e0">, c1.y</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r3.xyz</font><font color = "#e0e0e0">, r1.z</font><font color = "#e0e0e0">, c0.z</font><font color = "#a0a0a0"></font>
    mul <font color = "#e0e0e0">r1.z</font><font color = "#e0e0e0">, r1.w</font><font color = "#e0e0e0">, c1.x</font><font color = "#a0a0a0"></font>
    mov <font color = "#e0e0e0">r3.w</font><font color = "#e0e0e0">, c5.z</font><font color = "#a0a0a0"></font>
    lrp <font color = "#e0e0e0">r4</font><font color = "#e0e0e0">, r1.z</font><font color = "#e0e0e0">, r3</font><font color = "#e0e0e0">, r0</font><font color = "#a0a0a0"></font>
    mov <font color = "#e0e0e0">r2.w</font><font color = "#e0e0e0">, c5.z</font><font color = "#a0a0a0"></font>
    lrp <font color = "#e0e0e0">r0</font><font color = "#e0e0e0">, r1.x</font><font color = "#e0e0e0">, r2</font><font color = "#e0e0e0">, r4</font><font color = "#a0a0a0"></font>
    cmp <font color = "#e0e0e0">r0</font><font color = "#e0e0e0">, r1.y</font><font color = "#e0e0e0">, r4</font><font color = "#e0e0e0">, r0</font><font color = "#a0a0a0"></font>
    mov <font color = "#e0e0e0">oC0</font><font color = "#e0e0e0">, r0</font><font color = "#a0a0a0"></font>

</font><font color = "#a0a0a0">// approximately 85 instruction slots used (1 texture, 84 arithmetic)
</font>