chatCooldownSeconds: 0.5
defaultGameMode: boxing
plugins:
  titleInfo:
    updateSeconds: 4
  logs:
    webhookEnabled: true
    webhookPath: '/api/webhooks/xxxxx/xxxxxxxxxx'
modes:
  boxing:
    spawnX: 1617.59
    spawnY: 25.16
    spawnZ: 1199.76
    spawnSpacing: 1.75
    autoSpawn: true
