"""Convert Wavefront OBJ files for Suitium custom models.

The default output is a C++ header containing an expanded triangle list. The
game uploads that list to OpenGL when Suitium starts, so it does not depend on
Sub Rosa's internal CMO resource table. ``--cmo`` retains legacy CMO v3 output.
"""
import argparse
import math
import struct
from pathlib import Path


def index(value: str, size: int) -> int:
    value = int(value)
    return value - 1 if value > 0 else size + value


def parse(source: Path, scale: float = 1.0):
    positions, texcoords, triangles = [], [], []
    for raw in source.read_text(errors="replace").splitlines():
        fields = raw.split()
        if not fields or fields[0].startswith("#"):
            continue
        if fields[0] == "v" and len(fields) >= 4:
            positions.append(tuple(value * scale for value in map(float, fields[1:4])))
        elif fields[0] == "vt" and len(fields) >= 3:
            texcoords.append(tuple(map(float, fields[1:3])))
        elif fields[0] == "f" and len(fields) >= 4:
            face = []
            for token in fields[1:]:
                parts = token.split("/")
                position = positions[index(parts[0], len(positions))]
                uv = (0.0, 0.0)
                if len(parts) > 1 and parts[1]:
                    uv = texcoords[index(parts[1], len(texcoords))]
                face.append((position, (uv[0], 1.0 - uv[1])))
            for i in range(1, len(face) - 1):
                # Sub Rosa's shipped CMO meshes use the opposite winding from
                # ordinary Wavefront exports. Keep it here so native back-face
                # culling and generated lighting see the outside of the model.
                triangles.append((face[0], face[i + 1], face[i]))
    if not triangles:
        raise ValueError("OBJ contains no faces")
    return triangles


def expanded(triangles):
    out = []
    for triangle in triangles:
        a, b, c = (entry[0] for entry in triangle)
        ab = tuple(b[i] - a[i] for i in range(3))
        ac = tuple(c[i] - a[i] for i in range(3))
        normal = (ab[1] * ac[2] - ab[2] * ac[1], ab[2] * ac[0] - ab[0] * ac[2], ab[0] * ac[1] - ab[1] * ac[0])
        length = math.sqrt(sum(value * value for value in normal)) or 1.0
        normal = tuple(value / length for value in normal)
        for position, uv in triangle:
            out.append((*position, *uv, *normal))
    return out


def write_header(vertices, output: Path, symbol: str):
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", newline="\n") as target:
        target.write("// Generated by Tools/obj_to_cmo.py; do not edit by hand.\n#pragma once\n#include <array>\n\n")
        target.write("struct RuntimeModelVertex { float x, y, z, u, v, nx, ny, nz; };\n")
        target.write(f"inline constexpr std::array<RuntimeModelVertex, {len(vertices)}> {symbol}{{{{\n")
        for vertex in vertices:
            values = []
            for value in vertex:
                text = f"{value:.8g}"
                if "." not in text and "e" not in text.lower():
                    text += ".0"
                values.append(text + "f")
            target.write("    {" + ", ".join(values) + "},\n")
        target.write("}};\n")


def write_cmo(triangles, output: Path):
    # CMO is indexed. Expanding every triangle can overflow Sub Rosa's fixed
    # import scratch buffers on otherwise ordinary OBJ files.
    vertices = []
    vertex_indices = {}
    indexed_triangles = []
    for triangle in triangles:
        indices = []
        for vertex in triangle:
            if vertex not in vertex_indices:
                vertex_indices[vertex] = len(vertices)
                vertices.append(vertex)
            indices.append(vertex_indices[vertex])
        indexed_triangles.append(indices)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("wb") as target:
        target.write(b"CMod")
        target.write(struct.pack("<II", 3, len(vertices)))
        for (x, y, z), (u, v) in vertices:
            target.write(struct.pack("<6f", x, y, z, u, v, 0.0))
        target.write(struct.pack("<I", len(indexed_triangles)))
        for a, b, c in indexed_triangles:
            target.write(struct.pack("<I3III", 3, a, b, c, 0, 0))
        target.write(struct.pack("<I", 0))


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("source", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--symbol", default="runtimeModelVertices")
    parser.add_argument("--cmo", action="store_true", help="write legacy CMO instead of a C++ runtime mesh")
    parser.add_argument("--scale", type=float, default=1.0, help="uniform model scale applied during conversion")
    args = parser.parse_args()
    triangles = parse(args.source, args.scale)
    vertices = expanded(triangles)
    if args.cmo:
        write_cmo(triangles, args.output)
    else:
        write_header(vertices, args.output, args.symbol)
    print(f"wrote {len(vertices)} render vertices to {args.output}")
